;;; prelude-pack.el --- Prelude's default binding

;;; Commentary:

;;; Code:

(add-hook 'prelude-mode-hook
          (lambda ()
            (define-key prelude-mode-map (kbd "C-c o") 'prelude-open-with)
            (define-key prelude-mode-map (kbd "C-c g") 'prelude-google)
            (define-key prelude-mode-map (kbd "C-c G") 'prelude-github)
            (define-key prelude-mode-map (kbd "C-c y") 'prelude-youtube)
            (define-key prelude-mode-map (kbd "C-c U") 'prelude-duckduckgo)
            (define-key prelude-mode-map [(shift return)] 'prelude-smart-open-line)
            (define-key prelude-mode-map (kbd "M-o") 'prelude-smart-open-line)
            (define-key prelude-mode-map [(control shift return)] 'prelude-smart-open-line-above)
            (define-key prelude-mode-map [(control shift up)]  'move-text-up)
            (define-key prelude-mode-map [(control shift down)]  'move-text-down)
            (define-key prelude-mode-map [(meta shift up)]  'move-text-up)
            (define-key prelude-mode-map [(meta shift down)]  'move-text-down)
            (define-key prelude-mode-map (kbd "C-c n") 'prelude-cleanup-buffer)
            (define-key prelude-mode-map (kbd "C-c f")  'prelude-recentf-ido-find-file)
            (define-key prelude-mode-map (kbd "C-M-\\") 'prelude-indent-region-or-buffer)
            (define-key prelude-mode-map (kbd "C-M-z") 'prelude-indent-defun)
            (define-key prelude-mode-map (kbd "C-c u") 'prelude-view-url)
            (define-key prelude-mode-map (kbd "C-c e") 'prelude-eval-and-replace)
            (define-key prelude-mode-map (kbd "C-c s") 'prelude-swap-windows)
            (define-key prelude-mode-map (kbd "C-c D") 'prelude-delete-file-and-buffer)
            (define-key prelude-mode-map (kbd "C-c d") 'prelude-duplicate-current-line-or-region)
            (define-key prelude-mode-map (kbd "C-c M-d") 'prelude-duplicate-and-comment-current-line-or-region)
            (define-key prelude-mode-map (kbd "C-c r") 'prelude-rename-file-and-buffer)
            (define-key prelude-mode-map (kbd "C-c t") 'prelude-visit-term-buffer)
            (define-key prelude-mode-map (kbd "C-c k") 'prelude-kill-other-buffers)
            (define-key prelude-mode-map (kbd "C-c TAB") 'prelude-indent-rigidly-and-copy-to-clipboard)
            (define-key prelude-mode-map (kbd "C-c h") 'helm-prelude)
            (define-key prelude-mode-map (kbd "C-c +") 'prelude-increment-integer-at-point)
            (define-key prelude-mode-map (kbd "C-c -") 'prelude-decrement-integer-at-point)
            (define-key prelude-mode-map (kbd "C-c I") 'prelude-find-user-init-file)
            (define-key prelude-mode-map (kbd "C-c S") 'prelude-find-shell-init-file)
            (define-key prelude-mode-map [?\s-d] 'projectile-find-dir)
            (define-key prelude-mode-map [?\s-p] 'projectile-switch-project)
            (define-key prelude-mode-map [?\s-f] 'projectile-find-file)
            (define-key prelude-mode-map [?\s-g] 'projectile-grep)
            (define-key prelude-mode-map (kbd "s-r") 'prelude-recentf-ido-find-file)
            (define-key prelude-mode-map (kbd "s-j") 'prelude-top-join-line)
            (define-key prelude-mode-map (kbd "s-k") 'prelude-kill-whole-line)
            (define-key prelude-mode-map (kbd "s-m m") 'magit-status)
            (define-key prelude-mode-map (kbd "s-m l") 'magit-log)
            (define-key prelude-mode-map (kbd "s-m f") 'magit-file-log)
            (define-key prelude-mode-map (kbd "s-m b") 'magit-blame-mode)
            (define-key prelude-mode-map (kbd "s-o") 'prelude-smart-open-line-above)))

;;; prelude-pack.el ends here
